pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://api.xposed.info/' }
        // Jitpack kita taruh paling bawah sebagai opsi terakhir
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "fakegps-setter"
include ':app'
